org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Mod Properties
mod_id=fleshz
mod_name=FleshZ
mod_license=MIT
mod_version=0.0.4
mod_group_id=net.lxshh.fleshz
mod_authors=Lxshh, Globox_Z
mod_description=Extending the Leather obtaining process.
